### ISSUE TITLE
this.lastTime is not used

### ISSUE THREAD

**Issue by emersion** [Philmod/node-pid-controller#2]
[`this.lastTime`](https://github.com/Philmod/node-pid-controller/blob/master/lib/index.js#L11) is not used, is it because it's not needed anymore or because it's not implemented yet?

**Comment by Philmod** [comment]
Good point. You could add this in the `update` method.

**Comment by emersion** [comment]
Okay, will do :-)

**Comment by emersion** [comment]
Fixed in #3.
